version: '3'

services:
  app:
    image: ghcr.io/gitdeath/tabletop_scheduler:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/scheduler.db
    restart: always
